units_type: word
feature_source: AIhub
feature_type: mel-spectrogram
data:
    base_path: ./AIhub
    name: AIhub
    frame_rate: 60
    batch_size: 8
    encoding: True
    short_first: False
    shuffle: True
    feature_flag: feats.txt
    text_flag: targets.txt
    train: ./data/AIhub/train/
    dev: ./data/AIhub/dev/
    test: ./data/AIhub/test/
    left_context_width: 5
    right_context_width: 0
hparam:
    n_mel_channels: 80
    sampling_rate: 16000
    filter_length: 400
    hop_length: 160
    win_length: 400
    mel_fmin: 0.0
    mel_fmax: 8000.0
    max_wav_value: 32768.0
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 2048
        output_size: 2048
        projection_size: 640
        n_layers: 8
        bidirectional: False
    dec:
        type: lstm
        hidden_size: 2048
        output_size: 2048
        projection_size: 640
        n_layers: 2
    joint:
        input_size: 1280
        inner_size: 640
    vocab_size: 80
    share_weight: False
    feature_dim: 80
    stacking: 6
    backend: c++
training:
    load_model: False #./egs/AIhub/exp/aihub_test_beam_0910_enlen_noeos/aihub_test_beam_0910_enlen_noeos.epoch1650.chkpt
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epochs: 30
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_interval: 1
    save_model: aihub_q3_stream
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
