units_type: word
feature_source: AIhub
feature_type: mel-spectrogram
beam_size: 4
data:
    base_path: ./AIhub
    name: AIhub
    frame_rate: 30
    right_context_width: 1
    left_context_width: 1
    batch_size: 128
    encoding: True
    short_first: False
    short_train : False
    shuffle: True
    feature_flag: feats.txt
    text_flag: targets.txt
    train: ./data/AIhub/train/
    dev: ./data/AIhub/dev/
    test: ./data/AIhub/test/
    cleaner: korean_cleaners
    random_split: False
    train_set_percentage: 0.9
hparam:
    n_mel_channels: 80
    sampling_rate: 16000
    filter_length: 400
    hop_length: 160
    win_length: 400
    mel_fmin: 0.0
    mel_fmax: 8000.0
    max_wav_value: 32768.0
    max_abs_mel_value: 4.0
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 128
        output_size: 128
        n_layers: 3
        bidirectional: True
    dec:
        type: lstm
        hidden_size: 256
        output_size: 128
        n_layers: 1
    joint:
        input_size: 256
        inner_size: 128
    vocab_size: 80
    share_weight: False
    feature_dim: 80
    stacking: 3
    dropout: 0.3
    backend: c++
training:
    load_model: False #./best_model.chkpt
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    fp16_run: False
    dynamic_loss_scaling: True
    seed: 2019
    num_gpu: 1
    epochs: 300
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_interval: 1
    save_model: aihub_best
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.9
    weight_decay: 0
    begin_to_adjust_lr: 1000
