units_type: word
feature_source: AIhub
feature_type: mel-spectrogram
data:
    base_path: ./AIhub
    name: AIhub
    frame_rate: 10
    batch_size: 1
    encoding: True
    short_first: False
    shuffle: True
    feature_flag: feats_test.txt
    text_flag: targets_test.txt
    train: ./data/AIhub/train/
    dev: ./data/AIhub/dev/
    test: ./data/AIhub/test/
hparam:
    n_mel_channels: 80
    sampling_rate: 16000
    filter_length: 512
    hop_length: 128
    win_length: 512
    max_abs_mel_value: 4.0
    mel_fmin: 0.0
    mel_fmax: 8000.0
    max_wav_value: 32768.0
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 128
        output_size: 128
        n_layers: 3
        bidirectional: True
    dec:
        type: lstm
        hidden_size: 256
        output_size: 128
        n_layers: 1
    joint:
        input_size: 256
        inner_size: 128
    vocab_size: 80
    share_weight: False
    feature_dim: 80
    dropout: 0.3
    backend: c++
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epochs: 2000
    max_grad_norm: 200
    visualization: True
    show_interval: 50
    save_interval: 10
    save_model: aihub_test
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 1000
