units_type: character
feature_source: kaldi
feature_type: mfcc
data:
    name: toy
    vocab_feat: /home/chme/projects/rnn-transducer/data/toy/feature_vocab.txt
    vocab: /home/chme/projects/rnn-transducer/data/toy/target_vocab.txt #D:/RNN-Transducer/rnn-transducer/data/vocab.txt
    left_context_width: 1
    right_context_width: 0
    frame_rate: 10
    apply_cmvn: False
    max_input_length: 30
    max_target_length: 30
    batch_size: 1
    encoding: True
    short_first: False
    shuffle: False
    text_flag: target.txt
    train: /home/chme/projects/rnn-transducer/data/toy/train/ #D:/RNN-Transducer/rnn-transducer/data/train/
    dev: /home/chme/projects/rnn-transducer/data/toy/dev #D:/RNN-Transducer/rnn-transducer/data/dev/
    test: /home/chme/projects/rnn-transducer/data/toy/test #D:/RNN-Transducer/rnn-transducer/data/test/
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 32
        output_size: 32
        n_layers: 1
        bidirectional: False
    dec:
        type: lstm
        hidden_size: 32
        output_size: 32
        n_layers: 1
    joint:
        input_size: 64
        inner_size: 32
    vocab_size: 29
    share_weight: False
    feature_dim: 27
    dropout: 0.0
    backend: c++
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epochs: 100
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: toy_test
optim:
    type: sgd
    lr: 0.001
    momentum: 0.9
    decay_ratio: 0.99
    weight_decay: 0
    begin_to_adjust_lr: 10
